# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Migo' do

pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'ParseFacebookUtilsV4'
pod 'Bolts'
pod 'Parse'

end

target 'MigoTests' do

end

target 'MigoUITests' do

end

